apiVersion: apps/v1
kind: Deployment
metadata:
  name: contagem-env-deployment
  labels:
    app: contagem-env
spec:
  replicas: 4
  selector:
    matchLabels:
      app: contagem-env
  template:
    metadata:
      labels:
        app: contagem-env
    spec:
      containers:
      - name: contagem-env
        image: renatogroffe/apicontagem-env
        env:
          - name: TesteAmbiente
            value: Teste utilizando o Azure Kubernetes Service (AKS)
        ports:
        - containerPort: 80